name: 'Simple File Sync'
description: 'Synchronizes a file or directory from another git repository via Pull Request'

branding:
  icon: 'copy'
  color: 'gray-dark'

inputs:
  github_token:
    description: 'GitHub token (needs read access on source repo, write access on target)'
    required: true
  source_repo:
    description: 'Source repository (owner/repo for GitHub, or full URL for any git host)'
    required: true
  source_path:
    description: 'Path to file or directory in source repository'
    required: true
  source_branch:
    description: 'Branch to sync from in the source repository (defaults to the default branch)'
    required: false
    default: ''
  target_path:
    description: 'Destination path in current repository (defaults to source_path)'
    required: false
    default: ''
  target_branch:
    description: 'Target branch for the PR'
    required: false
    default: 'main'

outputs:
  pr_url:
    description: 'URL of the created or updated PR (empty if no changes)'
    value: ${{ steps.create-pr.outputs.pr_url }}
  pr_number:
    description: 'Number of the created or updated PR (empty if no changes)'
    value: ${{ steps.create-pr.outputs.pr_number }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      id: validate
      shell: bash
      env:
        SOURCE_REPO: ${{ inputs.source_repo }}
        SOURCE_PATH: ${{ inputs.source_path }}
        TARGET_PATH: ${{ inputs.target_path }}
      run: |
        # Validate source_repo format (owner/repo or full URL)
        if [[ "$SOURCE_REPO" =~ ^https?:// ]]; then
          SOURCE_URL="$SOURCE_REPO"
        elif [[ "$SOURCE_REPO" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
          SOURCE_URL="https://github.com/$SOURCE_REPO"
        else
          echo "::error::Invalid source_repo format: $SOURCE_REPO. Expected format: owner/repo or https://..."
          exit 1
        fi
        echo "source_url=$SOURCE_URL" >> "$GITHUB_OUTPUT"

        # Validate source_path is not empty
        if [[ -z "$SOURCE_PATH" ]]; then
          echo "::error::source_path cannot be empty"
          exit 1
        fi

        # Set target_path to source_path if not provided
        if [[ -z "$TARGET_PATH" ]]; then
          TARGET_PATH="$SOURCE_PATH"
        fi
        echo "target_path=$TARGET_PATH" >> "$GITHUB_OUTPUT"

        # Generate sanitized path for branch name
        SANITIZED_PATH=$(echo "$SOURCE_PATH" | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//' | cut -c1-30)
        echo "sanitized_path=$SANITIZED_PATH" >> "$GITHUB_OUTPUT"

    - name: Clone source repository
      id: clone
      shell: bash
      env:
        SOURCE_URL: ${{ steps.validate.outputs.source_url }}
        SOURCE_PATH: ${{ inputs.source_path }}
        SOURCE_BRANCH: ${{ inputs.source_branch }}
      run: |
        # Clone with sparse checkout for efficiency
        if [[ -n "$SOURCE_BRANCH" ]]; then
          git clone --depth 1 --filter=blob:none --sparse --branch "$SOURCE_BRANCH" "$SOURCE_URL" .sync-source
        else
          git clone --depth 1 --filter=blob:none --sparse "$SOURCE_URL" .sync-source
        fi
        cd .sync-source
        git sparse-checkout set "$SOURCE_PATH"

        # Get source commit SHA
        SOURCE_SHA=$(git rev-parse HEAD)
        SOURCE_SHORT_SHA=$(echo "$SOURCE_SHA" | cut -c1-7)
        echo "source_sha=$SOURCE_SHA" >> "$GITHUB_OUTPUT"
        echo "source_short_sha=$SOURCE_SHORT_SHA" >> "$GITHUB_OUTPUT"

    - name: Copy files and detect changes
      id: copy-files
      shell: bash
      env:
        SOURCE_PATH: ${{ inputs.source_path }}
        TARGET_PATH: ${{ steps.validate.outputs.target_path }}
      run: |
        SOURCE_FULL=".sync-source/$SOURCE_PATH"

        # Check if source exists
        if [[ ! -e "$SOURCE_FULL" ]]; then
          echo "::error::Source path does not exist: $SOURCE_PATH"
          exit 1
        fi

        # Determine if source is file or directory
        if [[ -d "$SOURCE_FULL" ]]; then
          echo "Syncing directory: $SOURCE_PATH -> $TARGET_PATH"

          # Remove trailing slashes for consistent behavior
          SOURCE_CLEAN="${SOURCE_FULL%/}"
          TARGET_CLEAN="${TARGET_PATH%/}"

          # Create target directory and sync contents
          mkdir -p "$TARGET_CLEAN"
          rm -rf "$TARGET_CLEAN"/*
          cp -r "$SOURCE_CLEAN"/* "$TARGET_CLEAN"/
        else
          echo "Syncing file: $SOURCE_PATH -> $TARGET_PATH"

          # Create parent directory if needed
          mkdir -p "$(dirname "$TARGET_PATH")"

          # Copy file
          cp "$SOURCE_FULL" "$TARGET_PATH"
        fi

        # Cleanup source checkout
        rm -rf .sync-source

        # Check for changes
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "No changes detected"
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
        else
          echo "Changes detected:"
          git status --short
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Create branch and commit
      id: commit
      if: steps.copy-files.outputs.has_changes == 'true'
      shell: bash
      env:
        SANITIZED_PATH: ${{ steps.validate.outputs.sanitized_path }}
        SOURCE_SHORT_SHA: ${{ steps.clone.outputs.source_short_sha }}
        SOURCE_REPO: ${{ inputs.source_repo }}
        SOURCE_URL: ${{ steps.validate.outputs.source_url }}
        SOURCE_PATH: ${{ inputs.source_path }}
        TARGET_PATH: ${{ steps.validate.outputs.target_path }}
      run: |
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Create branch name
        BRANCH_NAME="sync-files/${SANITIZED_PATH}-${SOURCE_SHORT_SHA}"
        echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

        # Create branch from current state (force-push will update remote if it exists)
        git checkout -B "$BRANCH_NAME"

        # Stage and commit changes
        git add -A
        git commit -m "Update $TARGET_PATH from $SOURCE_REPO@$SOURCE_SHORT_SHA"

        # Push (force to update if branch existed)
        git push -u origin "$BRANCH_NAME" --force

    - name: Create or update PR
      id: create-pr
      if: steps.copy-files.outputs.has_changes == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        BRANCH_NAME: ${{ steps.commit.outputs.branch_name }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        SOURCE_REPO: ${{ inputs.source_repo }}
        SOURCE_URL: ${{ steps.validate.outputs.source_url }}
        SOURCE_PATH: ${{ inputs.source_path }}
        TARGET_PATH: ${{ steps.validate.outputs.target_path }}
        SOURCE_SHA: ${{ steps.clone.outputs.source_sha }}
        SOURCE_SHORT_SHA: ${{ steps.clone.outputs.source_short_sha }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const branchName = process.env.BRANCH_NAME;
          const targetBranch = process.env.TARGET_BRANCH;
          const sourceRepo = process.env.SOURCE_REPO;
          const sourceUrl = process.env.SOURCE_URL;
          const sourcePath = process.env.SOURCE_PATH;
          const targetPath = process.env.TARGET_PATH;
          const sourceSha = process.env.SOURCE_SHA;
          const sourceShortSha = process.env.SOURCE_SHORT_SHA;

          const commitUrl = `${sourceUrl}/commit/${sourceSha}`;
          const prTitle = `Update ${targetPath} from ${sourceRepo} commit ${sourceShortSha}`;
          const prBody = `This PR updates ${targetPath} from [${sourceRepo}@${sourceShortSha}](${commitUrl}).

          ---

          *Automatically created by the [lbussell/sync-files](https://github.com/lbussell/sync-files) action.*`;

          // Check for existing PR
          const { data: existingPRs } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:${branchName}`,
            base: targetBranch,
            state: 'open'
          });

          let pr;
          if (existingPRs.length > 0) {
            pr = existingPRs[0];
            core.info(`Found existing PR #${pr.number}, branch updated`);
          } else {
            const { data: newPR } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              head: branchName,
              base: targetBranch,
              body: prBody
            });
            pr = newPR;
            core.info(`Created new PR #${pr.number}`);
          }

          core.setOutput('pr_url', pr.html_url);
          core.setOutput('pr_number', pr.number.toString());

    - name: Set empty outputs when no changes
      if: steps.copy-files.outputs.has_changes != 'true'
      shell: bash
      run: |
        echo "No changes detected, skipping PR creation"
